# Generated by Django 5.2 on 2025-04-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relative',
            name='relative_observations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='relative',
            name='relative_relationship',
            field=models.CharField(blank=True, choices=[('pai', 'Pai'), ('mae', 'Mãe'), ('irmao', 'Irmão'), ('irma', 'Irmã'), ('filho', 'Filho'), ('filha', 'Filha'), ('esposo', 'Esposo'), ('esposa', 'Esposa'), ('outro', 'Outro')], max_length=50),
        ),
    ]
