# Generated by Django 5.2 on 2025-04-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdata', '0004_remove_relative_id_relative_relative_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relative',
            name='relative_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='relative',
            name='relative_relationship',
            field=models.CharField(blank=True, choices=[('pai', 'Pai'), ('mae', 'Mãe'), ('irmao', 'Irmão'), ('irma', 'Irmã'), ('filho', 'Filho'), ('filha', 'Filha'), ('cônjuge', 'Cônjuge'), ('avô/avó', 'Avô/Avó'), ('neto/neta', 'Neto/Neta'), ('outro', 'Outro')], max_length=50),
        ),
    ]
