# Generated by Django 5.2 on 2025-04-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdata', '0005_alter_relative_relative_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='family_representative_gender',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='relative',
            name='relative_relationship',
            field=models.CharField(blank=True, choices=[('pai', 'Pai'), ('mae', 'Mãe'), ('irmao/irmã', 'Irmão/Irmã'), ('filho/filha', 'Filho/Filha'), ('cônjuge', 'Cônjuge'), ('avô/avó', 'Avô/Avó'), ('neto/neta', 'Neto/Neta'), ('outro', 'Outro')], max_length=50),
        ),
    ]
