# Generated by Django 5.2 on 2025-04-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdata', '0006_family_family_representative_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relative',
            name='relative_gender',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro')], max_length=10),
        ),
    ]
