# Generated by Django 5.2 on 2025-04-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdata', '0007_relative_relative_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='relative',
            name='relative_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
