# Generated by Django 5.2 on 2025-04-11 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdata', '0008_relative_relative_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(db_index=True, max_length=100)),
                ('event_date', models.DateField()),
                ('event_location_street', models.CharField(max_length=65)),
                ('event_location_number', models.CharField(max_length=10)),
                ('event_location_neighborhood', models.CharField(max_length=65)),
                ('event_location_city', models.CharField(max_length=65)),
                ('event_location_state', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='SP', max_length=2)),
                ('event_location_zipcode', models.CharField(blank=True, max_length=10)),
                ('event_location_complement', models.CharField(blank=True, max_length=255)),
                ('event_website', models.URLField(blank=True)),
                ('event_social_media', models.CharField(blank=True, max_length=255)),
                ('event_contact_person', models.CharField(blank=True, max_length=100)),
                ('event_contact_phone', models.CharField(blank=True, max_length=15)),
                ('event_contact_email', models.EmailField(blank=True, max_length=254)),
                ('event_description', models.TextField(blank=True)),
                ('event_note', models.TextField(blank=True)),
                ('event_created', models.DateTimeField(auto_now_add=True)),
                ('event_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('institution_id', models.AutoField(primary_key=True, serialize=False)),
                ('institution_name', models.CharField(db_index=True, max_length=100)),
                ('institution_type', models.CharField(blank=True, choices=[('comunitária', 'Comunitária'), ('privada', 'Privada'), ('pública', 'Pública'), ('religiosa', 'Religiosa'), ('outra', 'Outra')], max_length=11)),
                ('institution_cnpj', models.CharField(blank=True, max_length=14, unique=True)),
                ('institution_address_street', models.CharField(max_length=65)),
                ('institution_address_number', models.CharField(max_length=10)),
                ('institution_address_neighborhood', models.CharField(max_length=65)),
                ('institution_address_city', models.CharField(max_length=65)),
                ('institution_address_state', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='SP', max_length=2)),
                ('institution_address_zipcode', models.CharField(blank=True, max_length=10)),
                ('institution_address_complement', models.CharField(blank=True, max_length=255)),
                ('institution_phone', models.CharField(blank=True, max_length=15)),
                ('institution_email', models.EmailField(blank=True, max_length=254)),
                ('institution_website', models.URLField(blank=True)),
                ('institution_social_media', models.CharField(blank=True, max_length=255)),
                ('institution_description', models.TextField(blank=True)),
                ('institution_note', models.TextField(blank=True)),
                ('institution_created', models.DateTimeField(auto_now_add=True)),
                ('institution_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='relative',
            name='relative_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.CreateModel(
            name='FamilyEvent',
            fields=[
                ('family_event_id', models.AutoField(primary_key=True, serialize=False)),
                ('family_event_registration_date', models.DateTimeField(auto_now_add=True)),
                ('family_event_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_events', to='sdata.event')),
                ('family_event_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_events', to='sdata.family')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyEventInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('family_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution_assignment', to='sdata.familyevent')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_family_events', to='sdata.institution')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='sdata.institution'),
        ),
        migrations.CreateModel(
            name='InstitutionEvent',
            fields=[
                ('institution_event_id', models.AutoField(primary_key=True, serialize=False)),
                ('institution_event_registration_date', models.DateTimeField(auto_now_add=True)),
                ('institution_event_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_events', to='sdata.event')),
                ('institution_event_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_events', to='sdata.institution')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionRepresentative',
            fields=[
                ('institution_representative_id', models.AutoField(primary_key=True, serialize=False)),
                ('institution_representative_name', models.CharField(db_index=True, max_length=100)),
                ('institution_representative_gender', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro')], max_length=10)),
                ('institution_representative_birthdate', models.DateField(blank=True, null=True)),
                ('institution_representative_id_number', models.CharField(max_length=14, unique=True)),
                ('institution_representative_address_street', models.CharField(max_length=65)),
                ('institution_representative_address_number', models.CharField(max_length=10)),
                ('institution_representative_address_neighborhood', models.CharField(max_length=65)),
                ('institution_representative_address_city', models.CharField(max_length=65)),
                ('institution_representative_address_state', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='SP', max_length=2)),
                ('institution_representative_address_zipcode', models.CharField(blank=True, max_length=10)),
                ('institution_representative_address_complement', models.CharField(blank=True, max_length=255)),
                ('institution_representative_phone', models.CharField(blank=True, max_length=15)),
                ('institution_representative_email', models.EmailField(blank=True, max_length=254)),
                ('institution_representative_note', models.TextField(blank=True)),
                ('institution_representative_created', models.DateTimeField(auto_now_add=True)),
                ('institution_representative_updated', models.DateTimeField(auto_now=True)),
                ('institution_representative_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='sdata.institution')),
            ],
        ),
    ]
