# Generated by Django 5.2 on 2025-04-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdata', '0009_event_institution_alter_relative_relative_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='institution_cnpj',
            field=models.CharField(blank=True, max_length=18, unique=True),
        ),
    ]
