# Generated by Django 5.2 on 2025-04-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdata', '0010_alter_institution_institution_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyevent',
            name='served',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familyeventinstitution',
            name='served',
            field=models.BooleanField(default=False),
        ),
    ]
